config/routes.rb
Rails.application.routes.draw do

  #resources :task
  root 'tasks#index'

  get '/tasks', to: 'tasks#index'
  post '/tasks', to: 'tasks#create'

  get '/task/new', to: 'tasks#new'

  get '/task/:id/edit', to: 'tasks#edit', as: :edit_task

  get '/task/:id', to: 'tasks#show', as: :task
  patch '/task/:id', to: 'tasks#update'
  delete '/task/:id', to: 'tasks#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.text_field :name %>
  <p>Mark as done <%= f.check_box :done %></p>
  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Editeur de Tâches</h1>

<%= render "form" %>

app/views/tasks/index.html.erb
<div class="text-center"><h1>Liste des tâches</h1>
<p>Il y a du boulot</p>
<br>
<p><%= link_to "Créer une nouvelle tâche", task_new_path %></p>
<% @tasks.each do |task| %>
  <h2><%=  link_to task.name, task_path(task) %></h2>
    <%= form_for task do |f| %>
    <p>Mark as done : <%= f.check_box :done %></p>
    <% end %>
<% end %>

</div>

app/views/tasks/new.html.erb
<div class="text-center margin-top"><h1>Nouvelle Tâche</h1>
<p>Que voulez vous faire/qu'avez vous fait ?</p>

<%= render "form" %>
</div>

app/views/tasks/show.html.erb
<div class="text-center"><h1>Votre tâche</h1>
<p></p>
<h2><%= @task.name %></h2>
<p><% @task.done %></p>





<%= link_to "Back to tasks", tasks_path %>
<br>
 <%= link_to "Edit", edit_task_path(@task) %>
 <br>
 <%= link_to "Delete", task_path(@task), method: :delete %>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>